# Generated by Django 5.2.8 on 2025-11-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_jp', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketIndexType',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jp', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.country')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('symbol', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('memo', models.TextField(blank=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.industry')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stocks.market')),
            ],
        ),
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gdp_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.market')),
                ('index_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.marketindextype')),
            ],
        ),
        migrations.AddField(
            model_name='industry',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='stocks.sector'),
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.company')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('adjusted_index', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.industry')),
            ],
            options={
                'ordering': ['industry', 'date'],
                'constraints': [models.UniqueConstraint(fields=('industry', 'date'), name='unique_industry_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='market',
            constraint=models.UniqueConstraint(fields=('name', 'country'), name='unique_market_per_country'),
        ),
        migrations.AddConstraint(
            model_name='marketindex',
            constraint=models.UniqueConstraint(fields=('market', 'index_type', 'date'), name='unique_market_index'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['company', 'date'], name='stocks_stoc_company_faf5ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockprice',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='unique_company_date'),
        ),
    ]
