# Generated by Django 5.2.8 on 2025-11-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='company',
            name='name_jp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(editable=False, max_length=17, primary_key=True, serialize=False),
        ),
    ]
