# Generated by Django 5.2.8 on 2025-11-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_name_company_name_en_company_name_jp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='dividend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='split_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
