# Generated by Django 5.2.8 on 2026-02-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stockprice_dividend_stockprice_split_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('name_en__gt', ''), ('name_jp__gt', ''), _connector='OR'), name='name_en_or_name_jp_required'),
        ),
    ]
